GET http://localhost:4000/createTables

###
POST http://localhost:4000/messages/contactUs
Content-Type: application/json

{
    "name": "Armando Fernandez",
    "email": "armandof@gmail.com",
    "subject": "Website Development",
    "message": "Good day Sir, Im from A company called MediaTeck and would like to request a Project management website development Quotation.",
    "site": "www.test.com"
}